# Generated by Django 4.2.2 on 2024-04-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsModule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('battery', models.FloatField()),
                ('simNumber', models.CharField(max_length=15)),
                ('idEnfant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GpsCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('gpsModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_coordinates', to='position.gpsmodule')),
            ],
        ),
    ]
