# Generated by Django 5.0.4 on 2024-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_delete_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsmodule',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
