# Generated by Django 5.0.4 on 2024-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_alter_gpsmodule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsmodule',
            name='IMEI',
            field=models.CharField(default=123456789012345, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpsmodule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
