# Generated by Django 5.0.4 on 2024-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_gpsmodule_imei_alter_gpsmodule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsmodule',
            name='IMEI',
        ),
        migrations.AlterField(
            model_name='gpsmodule',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
