# Generated by Django 4.2.2 on 2024-06-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_remove_gpsmodule_imei_alter_gpsmodule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsmodule',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
